### ISSUE TITLE
Will be enabled the mouse in the future?

### ISSUE THREAD

**Issue by jrcribb** [Elius94/console-gui-tools#43]
Hi, excelent work. I'va a question: Will be enabled the mouse in the future?

**Comment by Elius94** [comment]
Thanks a lot Jorge :)
Mouse click is on the todo list but I think that it will be so hard to do.
That's because there's no Node.js terminal mouse click channel input.
Please, feel free to figure it out and maybe fire a PR on this repo.
Thanks a lot.

*Elia Lazzari*
*https://www.eliusoutdoor.com <https://www.eliusoutdoor.com/> - Outdoor
adventure photography*
Instagram profile <https://www.instagram.com/eliusoutdoor> | Facebook
profile <https://www.facebook.com/eliusoutdoor> | *YouTube Channel
<https://www.youtube.com/channel/UCptSWB5t8GBPGD3HifNBY9A> *
*tel: +39 345 4483546 <+393454483546> *

*Supported by*



Il giorno mar 8 nov 2022 alle ore 21:13 Jorge Ronald Cribb <
***@***.***> ha scritto:

**Comment by Elius94** [comment]
Hi! I tried this thing and it's working on Linux bash (on windows it only works running node in a WSL shell).

https://github.com/TooTallNate/keypress

I can integrate this but I prefere to find a way to make it works also on windows firs.

**Comment by Elius94** [comment]
>Changed the mouse terminal protocol to SGR
Now mouse evets are captured and managed in the ConsoleManager class.
the event is fired by MouseManager Instance:
event name: `mouseevent`
event data:
```ts
export interface MouseEventArgs {
    shift: boolean;
    alt: boolean;
    ctrl: boolean;
    // , pressed: pressed
    x: number;
    y: number;
    code: number;
    left: boolean;
    right: boolean;
    xFrom: number | null;
    yFrom: number | null;
}

export interface MouseEvent {
    name: string;
    eaten: number;
    data: MouseEventArgs;
}
```

##TODO:
- Propagate this event to the widget.
- Make them able to manage theese kind of events:
 - Drag boxes
 - Click on buttons
 - Scroll up and down (with click and wheel)

## Screenshot:
![mouse](https://user-images.githubusercontent.com/14907987/201684794-5897f2b0-386b-4066-bfdb-5d3fba9f58e3.gif)
